// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/serviceRepo.go
//
// Generated by this command:
//
//	mockgen -source=internal/storage/serviceRepo.go -destination=internal/mocks/serviceRepo.go -package mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	models "kong-assignment/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceRepo is a mock of ServiceRepo interface.
type MockServiceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockServiceRepoMockRecorder
}

// MockServiceRepoMockRecorder is the mock recorder for MockServiceRepo.
type MockServiceRepoMockRecorder struct {
	mock *MockServiceRepo
}

// NewMockServiceRepo creates a new mock instance.
func NewMockServiceRepo(ctrl *gomock.Controller) *MockServiceRepo {
	mock := &MockServiceRepo{ctrl: ctrl}
	mock.recorder = &MockServiceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceRepo) EXPECT() *MockServiceRepoMockRecorder {
	return m.recorder
}

// GetServices mocks base method.
func (m *MockServiceRepo) GetServices(queryParams models.QueryParams) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServices", queryParams)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServices indicates an expected call of GetServices.
func (mr *MockServiceRepoMockRecorder) GetServices(queryParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServices", reflect.TypeOf((*MockServiceRepo)(nil).GetServices), queryParams)
}

// SearchService mocks base method.
func (m *MockServiceRepo) SearchService(queryParams models.QueryParams) ([]models.Service, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchService", queryParams)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchService indicates an expected call of SearchService.
func (mr *MockServiceRepoMockRecorder) SearchService(queryParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchService", reflect.TypeOf((*MockServiceRepo)(nil).SearchService), queryParams)
}
